<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('fabricante.nombre', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Nombre del Fabricante"'), NULL, 'Nombre','Ejemplo: Trupper'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('fabricante.observacion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Observacion del Fabricante"', 'autocomplete'=>'off'), NULL, 'Observación','Sorporte Tecnico'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Fabricante'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
