<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/mano_obra/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/mano_obra/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/mano_obra/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="mano_obra">mano_obra</th>
                    <th class="col-collapse" data-search="mano_obra_slug">mano_obra SLUG</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($mano_obras->items as $mano_obra): ?>
                    <?php $key_upd = DwSecurity::getKey($mano_obra->id, 'upd_mano_obra'); ?>
                    <?php $key_del = DwSecurity::getKey($mano_obra->id, 'del_mano_obra'); ?>
                    <tr>
                        <td><?php echo $mano_obras->counter; ?></td>
                        <td><?php echo $mano_obra->sucursal; ?></td>
                        <td><?php echo $mano_obra->mano_obra; ?></td>
                        <td><?php echo $mano_obra->mano_obra_slug; ?></td>
                        <td><?php echo $mano_obra->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar mano_obra', "config/mano_obra/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar mano_obra', "config/mano_obra/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar mano_obra', 'confirm-body'=>'Está seguro de eliminar esta mano_obra? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $mano_obras->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$mano_obras, 'url'=>"config/mano_obra/listar/$order/")); ?>

</div>
