<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('marca.nombre', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), $marca->nombre, 'Profesion'); ?>
            </div>
      
            <div class="span6">
                <?php echo DwForm::text('marca.observacion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error'), $marca->observacion
                , 'Observacion'); ?>
            </div>
        </div>
        

            <?php echo DwForm::hiddenKey('marca.id', $marca->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar marca'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>