<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

		<div class="row-fluid">
            <div class="span4">
                 <?php echo DwForm::text('falla.falla', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Nombre de la falla"'), NULL, 'Nombre de la falla','Ejemplo Upsa Piritu, Biceabasto La Colonia'); ?>
            </div>
            <div class="span4">
				<?php echo DwForm::dbSelect('falla.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), $falla->pais_id, 'País'); ?>
            </div>
            <div class="span4">
                <div id='div_estado'><?php echo DwForm::dbSelect('falla.estado_id', 'nombre', array('params/estado', 'getListadoEstado'), $falla->estado_id, array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Estado'); ?></div>
            </div>
        </div>
        <div class="row-fluid">
             <div class="span4">
                <div id='div_municipio'><?php echo DwForm::dbSelect('falla.municipio_id', 'nombre', array('params/municipio', 'getListadoMunicipio'), $falla->municipio_id, array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Municipio'); ?></div>
            </div>
            <div class="span4">
                <div id='div_parroquia'><?php echo DwForm::dbSelect('falla.parroquia_id', 'nombre', array('params/parroquia', 'getListadoParroquia'), $falla->parroquia_id, array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Parroquia'); ?></div>
            </div>
             <div class="span4">
                <?php echo DwForm::text('falla.direccion', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Dirección"'), NULL, 'Dirección'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::tel('falla.celular', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Telefono Movil"'), NULL, 'Telefono Movil','Ejemplo 04143554584'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('falla.telefono', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Telefono Fijo"'), NULL, 'Teléfono Fijo','Ejemplo 02556210536'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('falla.fax', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Numero del Fax"'), NULL, 'Fax','Ejempo 02556221023'); ?>
            </div>
        </div>
            <?php echo DwForm::hiddenKey('falla.id', $falla->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar falla'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#falla_pais_id").click(function(){
    var pais_id     =   $('#falla_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'config/falla/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>
