<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/falla/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/falla/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/falla/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="falla">falla</th>
                    <th class="col-collapse" data-search="falla_slug">falla SLUG</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($fallas->items as $falla): ?>
                    <?php $key_upd = DwSecurity::getKey($falla->id, 'upd_falla'); ?>
                    <?php $key_del = DwSecurity::getKey($falla->id, 'del_falla'); ?>
                    <tr>
                        <td><?php echo $fallas->counter; ?></td>
                        <td><?php echo $falla->sucursal; ?></td>
                        <td><?php echo $falla->falla; ?></td>
                        <td><?php echo $falla->falla_slug; ?></td>
                        <td><?php echo $falla->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar falla', "config/falla/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar falla', "config/falla/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar falla', 'confirm-body'=>'Está seguro de eliminar esta falla? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $fallas->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$fallas, 'url'=>"config/falla/listar/$order/")); ?>

</div>
