<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
	
        <div class="row-fluid">    
             <div class="span4">
                <?php echo DwForm::text('equipo_herramienta.descripcion', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Descripción"'), NULL, 'Descripción'); ?>
            </div>
             <div class="span4">
                <?php echo DwForm::text('equipo_herramienta.observacion', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Observación"'), NULL, 'Observación'); ?>
            </div>
        </div>
            <?php echo DwForm::hiddenKey('equipo_herramienta.id', $equipo_herramienta->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar equipo_herramienta'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>