<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
		<div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::dbSelect('sector.sucursal_id', 'sucursal', array('params/sucursal', 'getListadoSucursal'), NULL, array('class'=>'input-xlarge input-required input-list show-errors data-toggle="tooltip" title="Seleccione la Sucursal"'), NULL, 'Sucursal','Ejemplo Piritu I'); ?>
            </div>       
            <div class="span4">
                <?php echo DwForm::text('sector.sector', array('class'=>'input-xlarge input-required mask-alpha show-error data-toggle="tooltip" title="Sector"'), NULL, 'Nombre del Sector'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('sector.observacion', array('class'=>'input-xlarge mask-alpha show-error data-toggle="tooltip" title="Observación"'), NULL, 'Observación'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar sector'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#sector_pais_id").click(function(){
    var pais_id     =   $('#sector_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'config/sector/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>
