<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/sector/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/sector/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/sector/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="sector">SECTOR</th>
                    <th class="col-collapse" data-search="sector_slug">SECTOR SLUG</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($sectores->items as $sector): ?>
                    <?php $key_upd = DwSecurity::getKey($sector->id, 'upd_sector'); ?>
                    <?php $key_del = DwSecurity::getKey($sector->id, 'del_sector'); ?>
                    <tr>
                        <td><?php echo $sectores->counter; ?></td>
                        <td><?php echo $sector->sucursal; ?></td>
                        <td><?php echo $sector->sector; ?></td>
                        <td><?php echo $sector->sector_slug; ?></td>
                        <td><?php echo $sector->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar sector', "config/sector/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar sector', "config/sector/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar sector', 'confirm-body'=>'Está seguro de eliminar esta sector? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $sectores->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$sectores, 'url'=>"config/sector/listar/$order/")); ?>

</div>
