<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::date('incidencia.fecha_solicitud', array('class'=>'input-required mask-date readonly input-date show-errors'), date("Y/m/d"), 'Fecha Solicitud'); ?>
            </div>
            
            <div class="span3">
              <label>UPSA:</label>
                <div id='div_upsa'>
                  <select class="input-large"> <option value=""> Seleccione:</option></select>
                </div>
            </div>
            
            <div class="span3">
                <?php echo DwForm::text('incidencia.departamento_id', array('class'=>'input-large input-required mask-alpha '), NULL, 'Departamento'); ?>
                <?php echo DwForm::hidden('incidencia.departamento_id', NULL, ''); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('incidencia.titular', array('class'=>'input-large mask-pint show-error input-required '), NULL, 'Cedula Titular'); ?>
                <?php echo DwForm::hidden('incidencia.titular_id', NULL, ''); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('incidencia.titular_idnombre', array('class'=>'input-large disabled '), NULL, 'Nombre Titular:'); ?>
            </div>
            <div class="span3">
				    <label>Beneficiarios:</label>
                <div id='div_beneficiario'>
                  <select class="input-large"> <option value=""> Seleccione:</option></select>
                </div>
            </div>
            <div class="span3">
                <?php echo DwForm::text('incidencia.servicio', array('class'=>'input-large input-required mask-alpha '), NULL, 'Servicio'); ?>
                <?php echo DwForm::hidden('incidencia.servicio_id', NULL, ''); ?>
            </div>
		    </div>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('incidencia.proveedor', array('class'=>'input-large input-required mask-alpha '), NULL, 'Proveedor'); ?>
                <?php echo DwForm::hidden('incidencia.proveedor_id', NULL, ''); ?>
            </div>
            <div class="span3">
               <?php echo DwForm::text('incidencia.medico', array('class'=>'input-large input-required mask-alpha'), NULL, 'Medico'); ?>
               <?php echo DwForm::hidden('incidencia.medico_id', NULL, ''); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('incidencia.observacion', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Observacion'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Solicitud'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
<script type="text/javascript" >
$(document).ready(function(){
  select: function ll(event, ui) {
                  $('input#incidencia_codigo_solicitud').val(ui.item.codid);// Asignacion de Id en Campo
                 // $('textarea#incidencia_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    
    $('input#incidencia_titular').autocomplete({
            minLength : 3 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>beneficiarios/titular/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#incidencia_titular_id').val(ui.item.id);// Asignacion de Id en Campo
                  $('input#incidencia_titular_idnombre').val(ui.item.idnombre);// Asignacion de Id en Campo
                 // $('textarea#incidencia_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    });
    $('input#incidencia_beneficiario').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>beneficiarios/beneficiario/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#incidencia_beneficiario_id').val(ui.item.id);// Asignacion de Id en Campo
                  $('input#incidencia_beneficiario_idnombre').val(ui.item.idnombre);// Asignacion de Id en Campo
              }
    });
    $( "input#incidencia_proveedor" ).autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/proveedor/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#incidencia_proveedor_id').val(ui.item.id);// Asignacion de Id en Campo
              }
    });
    $('input#incidencia_medico').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/medico/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#incidencia_medico_id').val(ui.item.id);// Asignacion de Id en Campo
              }
    });
    $('input#incidencia_servicio').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/servicio/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#incidencia_servicio_id').val(ui.item.id);// Asignacion de Id en Campo
                   //$('textarea#incidencia_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    }); 
$("#incidencia_titular").change(function(){
    var titular_id     =   $('#incidencia_titular_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/beneficiario/getBeneficiarios/'; ?>",
          data: "titular_id=" + titular_id,
          success: function(html){
            $("#div_beneficiario").html(html);
          }
        });
});
});
</script>
