<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row-fluid">
        <div class="span12">
            <p class="text-right">
                <span class="label label-success">BORRADOR</span>
                <span class="label">REGISTRADA</span>
                <span class="label">ASIGNADA</span>
                <span class="label">PROCESADA</span>
                <span class="label">CERRADA</span>
                <span class="label">ANULADA</span>
            </p>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span3">
            <?php echo DwForm::date('incidencia.fecha_solicitud', array('class' => 'input-required mask-date readonly input-date show-errors'), date("Y-m-d"), 'Fecha Solicitud'); ?>
        </div>
        <div class="span3">
            <?php echo DwForm::dbSelect('incidencia.sucursal_id', array('sucursal'), array('config/sucursal', 'getListadoSucursal'), NULL, array('class' => 'input-large input-required input-list show-errors'), NULL, 'Sucursal'); ?>
        </div>
        <div class="span3">
            <?php echo DwForm::dbSelect('incidencia.sector_id', array('sector'), array('config/sector', 'getListadoSector'), NULL, array('class' => 'input-large input-required input-list show-errors'), NULL, 'Sector'); ?>
        </div>
        <div class="span3">
            <?php echo DwForm::dbSelect('incidencia.equipo_id', array('codigo', 'nombre'), array('equipo/equipo', 'getListadoEquipo'), NULL, array('class' => 'input-large input-required input-list show-errors'), NULL, 'Equipo'); ?>
        </div>

    </div>

    <div class="row-fluid">
        <div class="span3">
            <?php echo DwForm::dbSelect('incidencia.falla_id', 'descripcion', array('config/falla', 'getListadoFalla'), NULL, array('class' => 'input-large input-required input-list show-errors'), NULL, 'Falla'); ?>
        </div>
        <div class="span3">
            <?php echo DwForm::select('incidencia.parada_sector', array('' => 'Seleccione:', 'true' => 'Si', 'false' => 'No'), array('class' => 'input-large input-required show-error data-toggle="tooltip" title="Parada del Sector" '), NULL, 'Parada de Sector:'); ?>
        </div>
        <div class="span3">
            <?php echo DwForm::select('incidencia.parada_planta', array('' => 'Seleccione:', 'true' => 'Si', 'false' => 'No'), array('class' => 'input-large input-required show-error data-toggle="tooltip" title="Parada de la Planta" '), NULL, 'Parada de la Planta:'); ?>
        </div>
        <div class="span3">
            <!--<?php echo DwForm::hidden('incidencia.motivo_parada_id', NULL, ''); ?>-->
            <?php echo DwForm::dbSelect('incidencia.motivo_parada_id', 'descripcion', array('config/motivo_parada', 'getListadoMotivo_parada'), NULL, array('class' => 'input-large input-required input-list show-errors'), NULL, 'Motivo de Parada:'); ?>

        </div>

    </div>
    <div class="row-fluid">
        <div class="span6">
            <?php echo DwForm::select('incidencia.turno', array('' => 'Seleccione:', 'DIURNO' => 'Diurno', 'NOCTURNO' => 'Nocturno'), array('class' => 'input-xlarge show-error data-toggle="tooltip" title="Turno" '), NULL, 'Turno:'); ?>
        </div>
        <div class="span6">
            <?php echo DwForm::textarea('incidencia.analisis_falla', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Analisis de Falla:'); ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::save('Guardar Solicitud'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel(); ?>
        </div>
    </div>
    <?php echo DwForm::close(); ?>
</div>
