<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row-fluid">
        <div class="span12">
            <p class="text-right">
                <span class="label">BORRADOR</span>
                <span class="label">REGISTRADA</span>
                <span class="label label-success">ASIGNADA</span>
                <span class="label">PROCESADA</span>
                <span class="label">CERRADA</span>
                <span class="label">ANULADA</span>
            </p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span8">
            <h4>Materiales y piezas</h4>
            <table id="items">
                <tr>
                    <th> Nombre</th>
                    <th> Descripcion</th>
                    <th> Cantidad</th>
                </tr>
                <tr class="item-row">
                    <td class="description">
                        <div class="delete-wpr"><input type="text" name="nombre[]" class="input-medium"><a
                                class="delete" href="javascript:;" title="Remove row">X</a></div>
                    </td>
                    <td><input type="text" name="descripcion[]" class="qty input-medium mask-num"></td>
                    <td><input type="text" name="cantidad[]" class="qty input-medium mask-num"></td>
                </tr>
                <tr id="hiderow">
                    <td colspan="6"><a id="addrow" href="javascript:;" title="Add a row">Agregar Material</a></td>
                </tr>
            </table>
        </div>
    </div>
    <hr>
    <div class="row-fluid">
        <div class="span12">
            <h4> Requisiciones de servicios </h4>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('requisicion_servicio.descripcion', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Descripcion:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('requision_servicio.trabajo_requerido', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Trabajo Requerido:'); ?>
            </div>


        </div>

    </div>

    <div class="row-fluid">
        <?php echo DwForm::hidden('incidencia.estatus', 'P'); ?>
        <div class="form-actions">
            <?php echo DwButton::save('Procesar Incidencia', 'cogs', '', 'PROCESAR'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel(); ?>
        </div>
    </div>
    <?php echo DwForm::close(); ?>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('input#incidencia_responsable_reparacion').autocomplete({
            minLength: 2, //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            /*focus: function( event, ui ) {
             $( "input#equipo_parte_caracteristica" ).val( ui.item.caracteristica );
             return false;
             },*/
            source: function (request, response) {
                $.ajax({
                    url: "<?php echo PUBLIC_PATH ?>sistema/usuario/autocomplete",
                    data: {'busqueda': request.term},
                    dataType: "json",
                    type: "POST",
                    success: function (data) {
                        response(data);
                    }
                });
            },
            select: function (event, ui) {
                $('input#incidencia_responsable_id').val(ui.item.id);// Asignacion de Id en Campo
                $('input#incidencia_responsable_reparacion').val(ui.item.nombre_completo);// Asignacion de Id en Campo
                // $('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
            }
        });
    });
</script>
