<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/turno/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/turno/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/turno/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="turno">SECTOR</th>
                    <th class="col-collapse" data-search="turno_slug">SECTOR SLUG</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($turnos->items as $turno): ?>
                    <?php $key_upd = DwSecurity::getKey($turno->id, 'upd_turno'); ?>
                    <?php $key_del = DwSecurity::getKey($turno->id, 'del_turno'); ?>
                    <tr>
                        <td><?php echo $turnos->counter; ?></td>
                        <td><?php echo $turno->sucursal; ?></td>
                        <td><?php echo $turno->turno; ?></td>
                        <td><?php echo $turno->turno_slug; ?></td>
                        <td><?php echo $turno->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar turno', "config/turno/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar turno', "config/turno/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar turno', 'confirm-body'=>'Está seguro de eliminar esta turno? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $turnos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$turnos, 'url'=>"config/turno/listar/$order/")); ?>

</div>
