<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::dbSelect('modelo.marca_id', 'nombre', array('config/marca', 'getListadoMarca'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Marca'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('modelo.nombre', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Nombre de la Modelo"'), NULL, 'Nombre'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('modelo.observacion', array('class'=>'input-xlarge input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Observacion de la Modelo"',), NULL, 'Observación'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Modelo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
