<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php if(Session::get('perfil_id')== 9) {

    ?>

    <div class="row">
        <div class="span12">
            <div class="widget stacked widget-table action-table">

                <div class="widget-header">
                    <i class="icon-th-list"></i>
                    <h3>Solicitudes Asignadas</h3>
                </div> <!-- /widget-header -->

                <div class="widget-content">

                    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                        <thead>
                        <tr>
                            <th class="col-collapse" data-search="fecha">FECHA</th>
                            <th class="col-collapse" data-search="hora_inicio">HORA INICIO</th>
                            <th class="col-collapse" data-search="planta">PLANTA</th>
                            <th class="col-collapse" data-search="sector">SECTOR</th>
                            <th class="col-collapse" data-search="equipo">EQUIPO</th>
                            <th class="col-collapse" >ACCIONES</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach($incidencias as $incidencia): ?>
                            <?php $key_prs = DwSecurity::getKey($incidencia->idincidencia, 'prs_incidencia'); ?>
                            <?php $key_del = DwSecurity::getKey($incidencia->idincidencia, 'del_incidencia'); ?>
                            <tr>
                                <td><?php $date = date_create($incidencia->fecha);
                                    echo date_format($date, "d-m-Y"); ?></td>
                                <td><?php echo $incidencia->hora_inicio; ?></td>
                                <td><?php echo $incidencia->sucursal; ?></td>
                                <td><?php echo $incidencia->sector; ?></td>
                                <td><?php echo $incidencia->codigo_equipo." ".$incidencia->nombre_equipo; ?></td>
                                <td>
                                    <?php
                                    echo DwHtml::buttonTable('Aprobar Incidencia', "incidencias/incidencia/procesar/$key_prs/", null, 'success', 'check');
                                    echo DwHtml::buttonTable('Vista previa ', "incidencias/incidencia/print_parcial/$key_prs/", null, 'info', 'print');
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div> <!-- /widget-content -->

            </div> <!-- /widget -->
        </div>

    </div>
    <div class="row">

        <div class="span4">
            <div class="widget stacked">

                <div class="widget-header">
                    <i class="icon-star"></i>
                    <h3>Total Solicitudes Procesadas</h3>
                </div> <!-- /widget-header -->
                <div class="widget-content">
                    Total Solicitudes: <b><?=  $total_solicitudes; ?></b>
                </div> <!-- /widget-content -->

            </div> <!-- /widget -->
        </div> <!-- /span6 -->
        <div class="span8">
            <div class="widget stacked">
                <div class="widget-header">
                    <i class="icon-signal"></i>
                    <h3>Ultimas 10 Solicitudes Completadas por Ti</h3>
                </div> <!-- /widget-header -->
                <div class="widget-content">
                    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                        <thead>
                        <tr>
                            <th class="col-collapse" data-search="fecha">FECHA</th>
                            <th class="col-collapse" data-search="hora_inicio">HORA INICIO</th>
                            <th class="col-collapse" data-search="planta">PLANTA</th>
                            <th class="col-collapse" data-search="sector">SECTOR</th>
                            <th class="col-collapse" data-search="equipo">EQUIPO</th>
                            <th class="col-collapse" >ACCIONES</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach($historico_incidencias as $h_incidencia): ?>
                            <?php $key_prs = DwSecurity::getKey($h_incidencia->idincidencia, 'prs_incidencia'); ?>
                            <?php $key_del = DwSecurity::getKey($h_incidencia->idincidencia, 'del_incidencia'); ?>
                            <tr>
                                <td><?php $date = date_create($h_incidencia->fecha);
                                    echo date_format($date, "d-m-Y"); ?></td>
                                <td><?php echo $h_incidencia->hora_inicio; ?></td>
                                <td><?php echo $h_incidencia->sucursal; ?></td>
                                <td><?php echo $h_incidencia->sector; ?></td>
                                <td><?php echo $h_incidencia->codigo_equipo." ".$h_incidencia->nombre_equipo; ?></td>
                                <td>
                                    <?php
                                    echo DwHtml::buttonTable('Ver Detalles ', "incidencias/incidencia/print_parcial/$key_prs/", null, 'info', 'print');
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>



                </div> <!-- /widget-content -->

            </div> <!-- /widget -->
        </div>

    </div>

</div> <!-- /row -->

<?php }
/**
 * Otro perfil
 */
elseif (Session::get('perfil_id')==3)  { ?>
    <h3>especialista<?php echo Session::get('nombre1').' '.Session::get('apellido1');?>  </h3>


<?php } elseif (Session::get('perfil_id')==7)  { ?>
    <div class="span12">
        <div class="widget stacked widget-table action-table">

            <div class="widget-header">
                <i class="icon-list-alt"></i>
                <h3>Cuenta Individual <?php echo Session::get('nombre1').' '.Session::get('apellido1');?>  </h3>
            </div> <!-- /widget-header -->

            <div class="widget-content">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th><h5>DATOS PERSONALES</h5></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><b>CEDULA DE IDENTIDAD:</b></td>
                        <td><?php echo $datostitular->cedula;?></td>
                        <td><b>NOMBRES:</b></td>
                        <td><?php echo $datostitular->nombre1.' '.$datostitular->nombre2;?></td>
                        <td><b>APELLIDOS:</b></td>
                        <td><?php echo $datostitular->apellido1.' '.$datostitular->apellido2;?></td>
                    </tr>
                    <tr>
                        <td><b>SEXO:</b></td>
                        <td><?php echo $datostitular->sexo;?></td>
                        <td><b>FECHA DE NACIMIENTO:<b></td>
                        <td><?php echo $datostitular->fecha_nacimiento;?></td>
                        <td><b>FECHA DE INGRESO:</b></td>
                        <td><?php echo $datostitular->fecha_ingreso;?></td>
                    </tr>
                    <tr>
                        <td><b>SEDE:</b></td>
                        <td><?php echo $datostitular->sucursal;?></td>
                        <td><b>DEPARTAMENTO:</b></td>
                        <td><?php echo $datostitular->departamento;?></td>
                        <td><b>CARGO:</b></td>
                        <td><?php echo $datostitular->cargo;?></td>
                    </tr>
                    <tr>
                        <td><b>TELEFONO LOCAL:</b></td>
                        <td><?php echo $datostitular->telefono;?></td>
                        <td><b>TELEFONO MOVIL:</b></td>
                        <td><?php echo $datostitular->celular;?></td>
                        <td><b>CORREO ELECTRONICO:<b></td>
                        <td><?php echo $datostitular->correo_electronico;?></td>
                    </tr>

                    </tbody>
                </table>

            </div> <!-- /widget-content -->
            <div class="widget-content">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th><h5>SALDOS CONSOLIDADOS TITULAR</h5></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><b>TOTAL SOLICITUDES:</b></td>
                        <td><b>SOLICITUDES MEDICINAS:</b></td>
                        <td><b>SOLICITUDES REEMBOLSOS:</b></td>
                        <td><b>SOLICITUDES CLINICAS:<b></td>
                    </tr>
                    <tr>
                        <td><?php echo ($hfarmacia_countitular[0]->count+$hreembolso_countitular[0]->count+$hclinica_countitular[0]->count);?></td>
                        <td><?php echo $hfarmacia_countitular[0]->count;?></td>
                        <td><?php echo $hreembolso_countitular[0]->count;?></td>
                        <td><?php echo $hclinica_countitular[0]->count;?></td>

                    </tr>
                    <tr>
                        <td><b>MONTO TOTAL SOLICITUDES:</b></td>
                        <td><b>MONTO SOLICITUDES MEDICINAS:</b></td>
                        <td><b>MONTO SOLICITUDES REEMBOLSOS:</b></td>
                        <td><b>MONTO SOLICITUDES CLINICAS:<b></td>
                    </tr>
                    <tr>
                        <td><?php echo ($hreembolso_montotitular[0]->sum+ $hfarmacia_montotitular[0]->sum+$hclinica_montotitular[0]->sum).' Bs.';?></td>
                        <td><?php echo $hfarmacia_montotitular[0]->sum.' Bs.';?></td>
                        <td><?php echo $hreembolso_montotitular[0]->sum.' Bs.';?></td>
                        <td><?php echo $hclinica_montotitular[0]->sum.' Bs.';?></td>

                    </tr>
                    </tbody>
                </table>

            </div> <!-- /widget-content -->

            <div class="widget-content">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th><h5>BENEFICIARIOS</h5></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><b>CEDULA DE IDENTIDAD:</b></td>
                        <td><b>NOMBRES:</b></td>
                        <td><b>APELLIDOS:</b></td>
                        <td><b>PARENTESCO:<b></td>
                        <td><b>FECHA NACIMIENTO:<b></td>

                    </tr>
                    <?php foreach($beneficiarios as $beneficiario): ?>
                        <tr>

                            <td><?php echo $beneficiario->cedula; ?></td>
                            <td><?php echo $beneficiario->nombre1.' '.$beneficiario->nombre2; ?></td>
                            <td><?php echo $beneficiario->apellido1.' '.$beneficiario->apellido2; ?></td>
                            <td><?php echo $beneficiario->parentesco; ?></td>
                            <td><?php echo $beneficiario->fecha_nacimiento; ?></td>

                        </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>

            </div> <!-- /widget-content -->
            <div class="widget-content">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th><h5>SALDOS CONSOLIDADOS BENEFICIARIOS</h5></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><b>TOTAL SOLICITUDES:</b></td>
                        <td><b>SOLICITUDES MEDICINAS:</b></td>
                        <td><b>SOLICITUDES REEMBOLSOS:</b></td>
                        <td><b>SOLICITUDES CLINICAS:<b></td>
                    </tr>
                    <tr>
                        <td><?php echo ($hfarmacia_countbeneficiario[0]->count+$hreembolso_countbeneficiario[0]->count+$hclinica_countbeneficiario[0]->count);?></td>
                        <td><?php echo $hfarmacia_countbeneficiario[0]->count;?></td>
                        <td><?php echo $hreembolso_countbeneficiario[0]->count;?></td>
                        <td><?php echo $hclinica_countbeneficiario[0]->count;?></td>

                    </tr>
                    <tr>
                        <td><b>MONTO TOTAL SOLICITUDES:</b></td>
                        <td><b>MONTO SOLICITUDES MEDICINAS:</b></td>
                        <td><b>MONTO SOLICITUDES REEMBOLSOS:</b></td>
                        <td><b>MONTO SOLICITUDES CLINICAS:<b></td>
                    </tr>
                    <tr>
                        <td><?php echo ($hreembolso_montobeneficiario[0]->sum+ $hfarmacia_montobeneficiario[0]->sum+$hclinica_montobeneficiario[0]->sum).' Bs.';?></td>
                        <td><?php echo $hfarmacia_montobeneficiario[0]->sum.' Bs.';?></td>
                        <td><?php echo $hreembolso_montobeneficiario[0]->sum.' Bs.';?></td>
                        <td><?php echo $hclinica_montobeneficiario[0]->sum.' Bs.';?></td>

                    </tr>
                    </tbody>
                </table>

            </div> <!-- /widget-content -->
        </div> <!-- /widget -->
    </div>


<?php } elseif (Session::get('perfil_id')==6) { ?>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Cuenta Individual  <?php echo Session::get('nombre1').' '.Session::get('apellido1');?> </a></li>
        <li ><a href="#tab2" data-toggle="tab">Gestión Enlace RRHH</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <div class="span12">
                <div class="widget stacked widget-table action-table">

                    <div class="widget-header">
                        <i class="icon-list-alt"></i>
                        <h3>Cuenta Individual <?php echo Session::get('nombre1').' '.Session::get('apellido1');?>  </h3>
                    </div> <!-- /widget-header -->

                    <div class="widget-content">

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th><h5>DATOS PERSONALES</h5></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><b>CEDULA DE IDENTIDAD:</b></td>
                                <td><?php echo $datostitular->cedula;?></td>
                                <td><b>NOMBRES:</b></td>
                                <td><?php echo $datostitular->nombre1.' '.$datostitular->nombre2;?></td>
                                <td><b>APELLIDOS:</b></td>
                                <td><?php echo $datostitular->apellido1.' '.$datostitular->apellido2;?></td>
                            </tr>
                            <tr>
                                <td><b>SEXO:</b></td>
                                <td><?php echo $datostitular->sexo;?></td>
                                <td><b>FECHA DE NACIMIENTO:<b></td>
                                <td><?php echo $datostitular->fecha_nacimiento;?></td>
                                <td><b>FECHA DE INGRESO:</b></td>
                                <td><?php echo $datostitular->fecha_ingreso;?></td>
                            </tr>
                            <tr>
                                <td><b>SEDE:</b></td>
                                <td><?php echo $datostitular->sucursal;?></td>
                                <td><b>DEPARTAMENTO:</b></td>
                                <td><?php echo $datostitular->departamento;?></td>
                                <td><b>CARGO:</b></td>
                                <td><?php echo $datostitular->cargo;?></td>
                            </tr>
                            <tr>
                                <td><b>TELEFONO LOCAL:</b></td>
                                <td><?php echo $datostitular->telefono;?></td>
                                <td><b>TELEFONO MOVIL:</b></td>
                                <td><?php echo $datostitular->celular;?></td>
                                <td><b>CORREO ELECTRONICO:<b></td>
                                <td><?php echo $datostitular->correo_electronico;?></td>
                            </tr>

                            </tbody>
                        </table>

                    </div> <!-- /widget-content -->
                    <div class="widget-content">

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th><h5>SALDOS CONSOLIDADOS TITULAR</h5></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><b>TOTAL SOLICITUDES:</b></td>
                                <td><b>SOLICITUDES MEDICINAS:</b></td>
                                <td><b>SOLICITUDES REEMBOLSOS:</b></td>
                                <td><b>SOLICITUDES CLINICAS:<b></td>
                            </tr>
                            <tr>
                                <td><?php echo ($hfarmacia_countitular[0]->count+$hreembolso_countitular[0]->count+$hclinica_countitular[0]->count);?></td>
                                <td><?php echo $hfarmacia_countitular[0]->count;?></td>
                                <td><?php echo $hreembolso_countitular[0]->count;?></td>
                                <td><?php echo $hclinica_countitular[0]->count;?></td>

                            </tr>
                            <tr>
                                <td><b>MONTO TOTAL SOLICITUDES:</b></td>
                                <td><b>MONTO SOLICITUDES MEDICINAS:</b></td>
                                <td><b>MONTO SOLICITUDES REEMBOLSOS:</b></td>
                                <td><b>MONTO SOLICITUDES CLINICAS:<b></td>
                            </tr>
                            <tr>
                                <td><?php echo ($hreembolso_montotitular[0]->sum+ $hfarmacia_montotitular[0]->sum+$hclinica_montotitular[0]->sum).' Bs.';?></td>
                                <td><?php echo $hfarmacia_montotitular[0]->sum.' Bs.';?></td>
                                <td><?php echo $hreembolso_montotitular[0]->sum.' Bs.';?></td>
                                <td><?php echo $hclinica_montotitular[0]->sum.' Bs.';?></td>

                            </tr>
                            </tbody>
                        </table>

                    </div> <!-- /widget-content -->

                    <div class="widget-content">

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th><h5>BENEFICIARIOS</h5></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><b>CEDULA DE IDENTIDAD:</b></td>
                                <td><b>NOMBRES:</b></td>
                                <td><b>APELLIDOS:</b></td>
                                <td><b>PARENTESCO:<b></td>
                                <td><b>FECHA NACIMIENTO:<b></td>

                            </tr>
                            <?php foreach($beneficiarios as $beneficiario): ?>
                                <tr>

                                    <td><?php echo $beneficiario->cedula; ?></td>
                                    <td><?php echo $beneficiario->nombre1.' '.$beneficiario->nombre2; ?></td>
                                    <td><?php echo $beneficiario->apellido1.' '.$beneficiario->apellido2; ?></td>
                                    <td><?php echo $beneficiario->parentesco; ?></td>
                                    <td><?php echo $beneficiario->fecha_nacimiento; ?></td>

                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>

                    </div> <!-- /widget-content -->
                    <div class="widget-content">

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th><h5>SALDOS CONSOLIDADOS BENEFICIARIOS</h5></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><b>TOTAL SOLICITUDES:</b></td>
                                <td><b>SOLICITUDES MEDICINAS:</b></td>
                                <td><b>SOLICITUDES REEMBOLSOS:</b></td>
                                <td><b>SOLICITUDES CLINICAS:<b></td>
                            </tr>
                            <tr>
                                <td><?php echo ($hfarmacia_countbeneficiario[0]->count+$hreembolso_countbeneficiario[0]->count+$hclinica_countbeneficiario[0]->count);?></td>
                                <td><?php echo $hfarmacia_countbeneficiario[0]->count;?></td>
                                <td><?php echo $hreembolso_countbeneficiario[0]->count;?></td>
                                <td><?php echo $hclinica_countbeneficiario[0]->count;?></td>

                            </tr>
                            <tr>
                                <td><b>MONTO TOTAL SOLICITUDES:</b></td>
                                <td><b>MONTO SOLICITUDES MEDICINAS:</b></td>
                                <td><b>MONTO SOLICITUDES REEMBOLSOS:</b></td>
                                <td><b>MONTO SOLICITUDES CLINICAS:<b></td>
                            </tr>
                            <tr>
                                <td><?php echo ($hreembolso_montobeneficiario[0]->sum+ $hfarmacia_montobeneficiario[0]->sum+$hclinica_montobeneficiario[0]->sum).' Bs.';?></td>
                                <td><?php echo $hfarmacia_montobeneficiario[0]->sum.' Bs.';?></td>
                                <td><?php echo $hreembolso_montobeneficiario[0]->sum.' Bs.';?></td>
                                <td><?php echo $hclinica_montobeneficiario[0]->sum.' Bs.';?></td>

                            </tr>
                            </tbody>
                        </table>

                    </div> <!-- /widget-content -->
                </div> <!-- /widget -->
            </div>

        </div><!--Cierre tab1-->

        <div class="tab-pane" id="tab2">
        </div><!--Cierre tab2-->
    </div>

<?php } elseif (Session::get('perfil_id')==8) { ?>
    <h3>proveedor<?php echo Session::get('nombre1').' '.Session::get('apellido1');?>  </h3>

<?php } else { ?>

<?php }  ?>

</div>
<?php
echo "<script language='JavaScript'>\n";
echo "var js_reembolsos = new Array();\n";
$ix = 0;
foreach($hreembolso_periodos as $key)
{
    echo "js_reembolsos[$key->mes] = $key->total_reembolsos;\n";
}
# .....rest of JavaScript..... 
echo "</script>\n";
?>
<?php
echo "<script language='JavaScript'>\n";
echo "var js_farmacias = new Array();\n";
$ix = 0;
foreach($hfarmacia_periodos as $key)
{
    echo "js_farmacias[$key->mes] = $key->total_farmacias;\n";
}
# .....rest of JavaScript..... 
echo "</script>\n";
?>
<?php
echo "<script language='JavaScript'>\n";
echo "var js_clinicas = new Array();\n";
$ix = 0;
foreach($hclinica_periodos as $key)
{
    echo "js_clinicas[$key->mes] = $key->total_clinicas;\n";
}
# .....rest of JavaScript..... 
echo "</script>\n";
?>
<script>

    var lineChartData = {
        labels : ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio"],
        datasets : [
            {
                label: "Farmacias",
                fillColor : "rgba(210,100,220,0.2)",
                strokeColor : "rgba(210,100,220,1)",
                pointColor : "rgba(210,100,220,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(210,100,220,1)",
                data : [js_farmacias[1],js_farmacias[2],js_farmacias[3],js_farmacias[4],js_farmacias[5],js_farmacias[6],js_farmacias[7]],
                title : 'Farmacias'
            },
            {
                label: "Clinicas",
                fillColor : "rgba(220,220,220,0.2)",
                strokeColor : "rgba(220,220,220,1)",
                pointColor : "rgba(220,220,220,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(220,220,220,1)",
                data : [js_clinicas[1],js_clinicas[2],js_clinicas[3],js_clinicas[4],js_clinicas[5],js_clinicas[6],js_clinicas[7]],
                title : 'Clinicas'
            },

            {
                label: "Reembolsos",
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                pointColor : "rgba(151,187,205,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(151,187,205,1)",
                data : [js_reembolsos[1],js_reembolsos[2],js_reembolsos[3],js_reembolsos[4],js_reembolsos[5],js_reembolsos[6],'0'],
                title : 'Reembolsos'
            }
        ]

    }

    var doughnutData = [
        {
            value: 300.34,
            color:"#F7464A",
            highlight: "#FF5A5E",
            label: "Monto Pagado Reembolsos",
            title: "Monto Pagado Reembolsos"

        },
        {
            value: 50,
            color: "#46BFBD",
            highlight: "#5AD3D1",
            label: "Monto Pagado Farmacias",
            title: "Monto Pagado Farmacias"

        },
        {
            value: 100,
            color: "#FDB45C",
            highlight: "#FFC870",
            label: "Monto Pagado Clinicas",
            title: "Monto Pagado Clinicas"

        }
    ];


    window.onload = function(){
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myLine = new Chart(ctx).Line(lineChartData, {
            responsive: true
        });
        legend(document.getElementById("lineLegend"), lineChartData);

        var ctx1 = document.getElementById("piechart").getContext("2d");
        window.myDoughnut = new Chart(ctx1).Doughnut(doughnutData, {responsive : true});
        legend(document.getElementById("pielegend"), doughnutData);

    }

</script>















       
