<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::dbSelect('parte.parte_categoria_id', 'nombre', array('config/parte_categoria', 'getListadoCategoria'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Categoria'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('parte.nombre', array('class'=>'input-large input-required show-error data-toggle="tooltip" title="Nombre"'), NULL, 'Nombre'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('parte.caracteristica', array('class'=>'input-large input-required input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Caracteristicas'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::textarea('parte.observacion', array('class'=>'input-large input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Observación'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Parte'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
