<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.nombre', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Nombre del Proveedor"'), NULL, 'Nombre','Ejemplo: Trupper'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('proveedor.direccion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Dirección del Proveedor"', 'autocomplete'=>'off'), NULL, 'Dirección','Av. Principal'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('proveedor.telefono', array('class'=>'input-numeric input-required input-xlarge mask-pint show-error data-toggle="tooltip" title="Ingrese Teléfono Fijo del Proveedor"'), NULL, 'Teléfono'); ?>
            </div>
             <div class="span3">
                <?php echo DwForm::email('proveedor.correo', array('class'=>'input-xlarge show-error data-toggle="tooltip" title="Ingrese Correo Electrónico del Proveedor"'), NULL, 'Correo Electrónico'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('proveedor.observacion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Observacion del Proveedor"', 'autocomplete'=>'off'), NULL, 'Observación','Sorporte Tecnico'); ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Proveedor'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
