<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('parte_categoria.nombre', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Categoria"'), NULL, 'Categoria'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('parte_categoria.observacion', array('class'=>'input-xlarge input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Descripción'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Categorias'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
