<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/material_recurso/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/material_recurso/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/material_recurso/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="descripcion">Descripción</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($material_recursos->items as $material_recurso): ?>
                    <?php $key_upd = DwSecurity::getKey($material_recurso->id, 'upd_material_recurso'); ?>
                    <?php $key_del = DwSecurity::getKey($material_recurso->id, 'del_material_recurso'); ?>
                    <tr>
                        <td><?php echo $material_recursos->counter; ?></td>
                        <td><?php echo $material_recurso->descripcion; ?></td>
                        <td><?php echo $material_recurso->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar material_recurso', "config/material_recurso/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar material_recurso', "config/material_recurso/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar material_recurso', 'confirm-body'=>'Está seguro de eliminar esta material_recurso? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $material_recursos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$material_recursos, 'url'=>"config/material_recurso/listar/$order/")); ?>

</div>
