<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
		<div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::dbSelect('tipo_trabajo.sucursal_id', 'sucursal', array('params/sucursal', 'getListadoSucursal'), NULL, array('class'=>'input-xlarge input-required input-list show-errors data-toggle="tooltip" title="Seleccione la Sucursal"'), NULL, 'Sucursal','Ejemplo Piritu I'); ?>
            </div>       
            <div class="span4">
                <?php echo DwForm::text('tipo_trabajo.tipo_trabajo', array('class'=>'input-xlarge input-required mask-alpha show-error data-toggle="tooltip" title="tipo_trabajo"'), NULL, 'Nombre del tipo_trabajo'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('tipo_trabajo.observacion', array('class'=>'input-xlarge mask-alpha show-error data-toggle="tooltip" title="Observación"'), NULL, 'Observación'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar tipo_trabajo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
