<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/tipo_trabajo/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/tipo_trabajo/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/tipo_trabajo/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="descripcion">Descripción</th>
                    <th class="col-collapse" data-search="observacion">observacion</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($tipo_trabajos->items as $tipo_trabajo): ?>
                    <?php $key_upd = DwSecurity::getKey($tipo_trabajo->id, 'upd_tipo_trabajo'); ?>
                    <?php $key_del = DwSecurity::getKey($tipo_trabajo->id, 'del_tipo_trabajo'); ?>
                    <tr>
                        <td><?php echo $tipo_trabajos->counter; ?></td>
                        <td><?php echo $tipo_trabajo->descripcion; ?></td>
                        <td><?php echo $tipo_trabajo->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar tipo_trabajo', "config/tipo_trabajo/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar tipo_trabajo', "config/tipo_trabajo/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar tipo_trabajo', 'confirm-body'=>'Está seguro de eliminar esta tipo_trabajo? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $tipo_trabajos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$tipo_trabajos, 'url'=>"config/tipo_trabajo/listar/$order/")); ?>

</div>
