<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    <?php if(DESKTOP) { ?>
     <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información del Equipo / Maquinaria</a></li>
            <li><a href="#tab2" data-toggle="tab">Especificaciones y Funcionamiento</a></li>
        </ul>
        <div class="tab-content">
        <div class="tab-pane active" id="tab1">
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('equipo.codigo', array('class'=>'input-large mask-alphanum'),NULL, 'Código:'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('equipo.activo_fijo', array('class'=>'input-large mask-pint show-error input-required '), NULL, 'Activo Fijo'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::date('equipo.fecha_registro', array('class'=>'input-required mask-date disabled readonly input-date show-errors'), date("d-m-Y"), 'Fecha Registro'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::date('equipo.fecha_compra', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha Adquisición'); ?>
            </div>
        </div>
        <div class="row-fluid">
             <div class="span3">
                <?php echo DwForm::dbSelect('equipo.marca_id', 'nombre', array('config/marca', 'getListadoMarca'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Marca'); ?>
            </div>
            <div class="span3">
              <?php echo DwForm::dbSelect('equipo.modelo_id', 'nombre', array('config/modelo', 'getListadoModelo'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Modelo'); ?>
            </div>
            <div class="span3">
              <?php echo DwForm::dbSelect('equipo.proveedor_id', 'nombre', array('config/proveedor', 'getListadoProveedor'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Proveedor'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('equipo.nombre', array('class'=>'input-large mask-alphanum input-required'), NULL, 'Nombre del Equipo'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
              <?php echo DwForm::dbSelect('equipo.sector_id', array('sector','sucursal'), array('config/sector', 'getListadoSector'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Sector'); ?>
            </div>
            <div class="span3">

              <?php echo DwForm::dbSelect('equipo.fabricante_id', 'nombre', array('config/fabricante', 'getListadoFabricante'), NULL, array('class'=>'input-large input-required input-list show-errors'), NULL, 'Fabricante'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('equipo.observacion', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Observación'); ?>
            </div>
        </div>
        </div><!-- FIN del tab 1 -->

        <div class="tab-pane" id="tab2">
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('equipo.caracteristicas', array('class'=>'input-xxlarge mask-alphanum input-required show-error'), NULL, 'Especificaciones y Caracteristicas principales'); ?>
            </div>
            <div class="span6"> 
                <?php echo DwForm::textarea('equipo.funcionamiento', array('class'=>'input-xxlarge mask-alphanum input-required show-error'), NULL, 'Funcionamiento y Manejo'); ?>
            </div>
        </div>
      </div><!-- Fin del TAB #03 FACTURAS-->
             <div class="row-fluid">
              <div class="form-actions">
                <?php echo DwButton::save('Guardar Equipo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
              </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>