<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"equipo/equipo/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("equipo/equipo/agregar", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>
    <div class="dw-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha_registro">FECHA REGISTRO </th>
                    <th class="col-collapse" data-search="fecha_adquisicion">FECHA COMPRA</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="fabricante">FABRICANTE</th>
                    <th class="col-collapse" data-search="marca">MARCA</th>
                    <th class="col-collapse" data-search="modelo">MODELO</th>
                    <th class="col-collapse" data-search="proveedor">PROVEEDOR</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="col-collapse" >ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php  foreach($equipos->items as $equipo): ?>
                    <?php $key_upd = DwSecurity::getKey($equipo->id, 'upd_equipo'); ?>
                    <?php $key_piece = DwSecurity::getKey($equipo->id, 'piece_equipo'); ?>
                    <tr>
                        <td><?php echo $equipos->counter; ?></td>
                        <td><?php echo date("d-m-Y", strtotime($equipo->fecha_registro)); ?></td>
                        <td><?php echo date("d-m-Y", strtotime($equipo->fecha_compra)); ?></td>
                        <td><?php echo $equipo->codigo; ?></td>
                        <td><?php echo $equipo->nombre; ?></td>
                        <td><?php echo $equipo->fabricante; ?></td>
                        <td><?php echo $equipo->marca; ?></td>
                        <td><?php echo $equipo->modelo; ?></td>
                        <td><?php echo $equipo->proveedor; ?></td>
                        <td><?php echo $equipo->estado_solicitud; ?></td>
                        
                        <td>
                            <?php echo DwHtml::buttonTable('Agregar Partes', "equipo/equipo/agregar_partes/$key_piece/", NULL, 'warning', 'cogs'); ?>
                            <?php echo DwHtml::buttonTable('Modificar Equipo', "equipo/equipo/", null, 'info', 'edit'); ?>
                        </td>
                    </tr>
                    <?php $equipos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

</div>
